-- Legacy compatibility pointer.
--
-- Do not run this file in the SQL editor. The canonical, complete Wander Bike
-- database schema is maintained as chronological files in:
--
--   supabase/migrations/
--
-- Apply them with `supabase db push` or the Supabase migration API so migration
-- history, RLS, functions, triggers, storage policies, and commerce tables stay
-- consistent.
