-- The marketplace has no shared production-like seed.
--
-- Public pages use in-code demo listings only when Supabase environment
-- variables are absent. Real Wander and community bikes must be created by an
-- authenticated owner so row ownership, private pickup details, and image
-- storage paths are valid.
