import type { CatalogProduct } from "@/lib/commerce/types";

export const demoCatalog: CatalogProduct[] = [
  {
    id: 1001,
    slug: "test-steveston-city-bike",
    name: "[TEST] Steveston City Bike",
    shortDescription: "Sandbox bicycle used to verify the complete sales workflow.",
    description:
      "This is test catalog data. No physical bicycle will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 1, slug: "bikes", name: "Bikes" },
    tags: ["sandbox", "bike", "city"],
    requiresShipping: true,
    images: [
      {
        id: 1001,
        src: "/assets/bikes-row.jpg",
        alt: "Rows of bicycles at Wander Bike — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1001,
        sku: "TEST-BIKE-CITY-M-GREEN",
        title: "Medium / Harbour Green",
        optionValues: { size: "Medium", colour: "Harbour Green" },
        priceCents: 89900,
        compareAtPriceCents: null,
        weightGrams: 13500,
        lengthCm: 170,
        widthCm: 25,
        heightCm: 95,
        canadaPostEligible: false,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
  {
    id: 1002,
    slug: "test-waterfront-comfort-bike",
    name: "[TEST] Waterfront Comfort Bike",
    shortDescription: "Sandbox comfort bike for pickup and shipping tests.",
    description:
      "This is test catalog data. No physical bicycle will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 1, slug: "bikes", name: "Bikes" },
    tags: ["sandbox", "bike", "comfort"],
    requiresShipping: true,
    images: [
      {
        id: 1002,
        src: "/assets/steveston-ride-idea.jpg",
        alt: "Bicycle near the Steveston waterfront — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1002,
        sku: "TEST-BIKE-COMFORT-M-NAVY",
        title: "Medium / Deep Navy",
        optionValues: { size: "Medium", colour: "Deep Navy" },
        priceCents: 74900,
        compareAtPriceCents: null,
        weightGrams: 14200,
        lengthCm: 175,
        widthCm: 27,
        heightCm: 98,
        canadaPostEligible: false,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
  {
    id: 1003,
    slug: "test-family-ride-helmet",
    name: "[TEST] Family Ride Helmet",
    shortDescription: "Sandbox helmet used for variant and tax testing.",
    description:
      "This is test catalog data. No physical helmet will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 2, slug: "accessories", name: "Accessories" },
    tags: ["sandbox", "helmet", "safety"],
    requiresShipping: true,
    images: [
      {
        id: 1003,
        src: "/assets/helmets.jpg",
        alt: "Bicycle helmets — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1003,
        sku: "TEST-HELMET-FAMILY-M-TEAL",
        title: "Medium / Teal",
        optionValues: { size: "Medium", colour: "Teal" },
        priceCents: 8900,
        compareAtPriceCents: null,
        weightGrams: 420,
        lengthCm: 32,
        widthCm: 24,
        heightCm: 20,
        canadaPostEligible: true,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
  {
    id: 1004,
    slug: "test-rear-market-basket",
    name: "[TEST] Rear Market Basket",
    shortDescription: "Sandbox accessory used for cart and fulfillment testing.",
    description:
      "This is test catalog data. No physical basket will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 2, slug: "accessories", name: "Accessories" },
    tags: ["sandbox", "basket", "accessory"],
    requiresShipping: true,
    images: [
      {
        id: 1004,
        src: "/assets/west-dyke-ride.webp",
        alt: "Bicycle prepared for a waterfront ride — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1004,
        sku: "TEST-BASKET-REAR-BLACK",
        title: "Black",
        optionValues: { colour: "Black" },
        priceCents: 6400,
        compareAtPriceCents: null,
        weightGrams: 1100,
        lengthCm: 42,
        widthCm: 32,
        heightCm: 28,
        canadaPostEligible: true,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
  {
    id: 1005,
    slug: "test-usb-front-light",
    name: "[TEST] USB Front Light",
    shortDescription: "Sandbox light used for multi-item checkout testing.",
    description:
      "This is test catalog data. No physical light will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 2, slug: "accessories", name: "Accessories" },
    tags: ["sandbox", "light", "accessory"],
    requiresShipping: true,
    images: [
      {
        id: 1005,
        src: "/assets/west-dyke-trail.jpg",
        alt: "Bicycle trail in Richmond — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1005,
        sku: "TEST-LIGHT-USB-BLACK",
        title: "Black",
        optionValues: { colour: "Black" },
        priceCents: 4900,
        compareAtPriceCents: null,
        weightGrams: 180,
        lengthCm: 12,
        widthCm: 8,
        heightCm: 6,
        canadaPostEligible: true,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
  {
    id: 1006,
    slug: "test-kids-trail-helmet",
    name: "[TEST] Kids Trail Helmet",
    shortDescription: "Sandbox kids helmet used for product-option testing.",
    description:
      "This is test catalog data. No physical helmet will be sold or shipped.",
    productType: "physical",
    brand: { id: 1001, slug: "wander-bike-test-lab", name: "Wander Bike Test Lab" },
    category: { id: 2, slug: "accessories", name: "Accessories" },
    tags: ["sandbox", "helmet", "kids"],
    requiresShipping: true,
    images: [
      {
        id: 1006,
        src: "/assets/helmets.jpg",
        alt: "Kids bicycle helmets — sandbox product image",
        width: null,
        height: null,
      },
    ],
    variants: [
      {
        id: 1006,
        sku: "TEST-HELMET-KIDS-S-MINT",
        title: "Small / Mint",
        optionValues: { size: "Small", colour: "Mint" },
        priceCents: 5900,
        compareAtPriceCents: null,
        weightGrams: 360,
        lengthCm: 28,
        widthCm: 22,
        heightCm: 18,
        canadaPostEligible: true,
        available: 5,
        isAvailable: true,
        allowBackorder: false,
      },
    ],
    isSandboxProduct: true,
  },
];
