import type { BikeListing } from "@/lib/marketplace/types";

const base = {
  ownerId: "00000000-0000-0000-0000-000000000001",
  currency: "CAD" as const,
  condition: "good" as const,
  minimumRentalHours: 2,
  availableQuantity: 1,
  city: "Richmond",
  province: "BC",
  availableFrom: null,
  availableUntil: null,
  rentalRules: "Bring photo ID. Pickup time is confirmed directly with the owner.",
  includedItems: ["Helmet", "Lock"],
  status: "active" as const,
  managementNote: null,
  publishedAt: "2026-07-26T18:00:00.000Z",
  createdAt: "2026-07-26T18:00:00.000Z",
  updatedAt: "2026-07-26T18:00:00.000Z",
};

export const demoListings: BikeListing[] = [
  {
    ...base,
    id: "10000000-0000-0000-0000-000000000001",
    source: "wander",
    slug: "wander-seaside-cruiser",
    title: "Seaside Cruiser",
    shortDescription: "An easy, upright ride for the Steveston waterfront.",
    description:
      "A comfortable step-through cruiser prepared by the Wander Bike team. It is ideal for relaxed rides around Steveston Village, Garry Point, and the West Dyke.",
    bikeType: "cruiser",
    brand: "Electra",
    model: "Townie",
    frameSize: "One size · 5′2″–6′0″",
    tireSize: "26-inch",
    offerMode: "rent_sale",
    rentalHourlyCents: 1200,
    rentalDailyCents: 4500,
    salePriceCents: 48500,
    pickupArea: "Steveston Village",
    approximateLatitude: 49.1264,
    approximateLongitude: -123.1841,
    availabilitySummary: "Available most days · same-day requests welcome",
    featured: true,
    images: [
      {
        id: "img-wander-1",
        src: "/assets/bikes-row.jpg",
        storagePath: null,
        alt: "Wander Bike cruiser prepared for pickup",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
  {
    ...base,
    id: "10000000-0000-0000-0000-000000000002",
    source: "wander",
    slug: "wander-west-dyke-hybrid",
    title: "West Dyke Hybrid",
    shortDescription: "A versatile bike for longer paved and gravel routes.",
    description:
      "A light hybrid with a relaxed geometry and wide gearing. Choose it for the West Dyke, Railway Greenway, or a full afternoon exploring Richmond.",
    bikeType: "hybrid",
    brand: "Giant",
    model: "Escape",
    frameSize: "Medium · 5′6″–5′11″",
    tireSize: "700C",
    offerMode: "rent",
    rentalHourlyCents: 1500,
    rentalDailyCents: 5200,
    salePriceCents: null,
    pickupArea: "Steveston Village",
    approximateLatitude: 49.1268,
    approximateLongitude: -123.1813,
    availabilitySummary: "Pickup between 9 AM and 7 PM",
    featured: true,
    images: [
      {
        id: "img-wander-2",
        src: "/assets/west-dyke-ride.webp",
        storagePath: null,
        alt: "Hybrid bike route along the West Dyke",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
  {
    ...base,
    id: "10000000-0000-0000-0000-000000000003",
    source: "wander",
    slug: "wander-family-trailer",
    title: "Family Bike Trailer",
    shortDescription: "A clean two-seat trailer for family rides.",
    description:
      "A two-seat child trailer inspected and cleaned by Wander Bike. Please confirm your bike axle and child sizes with us before pickup.",
    bikeType: "trailer",
    brand: "Burley",
    model: "Bee",
    frameSize: "Two seats",
    tireSize: "20-inch",
    offerMode: "sale",
    rentalHourlyCents: null,
    rentalDailyCents: null,
    salePriceCents: 29500,
    pickupArea: "Steveston Village",
    approximateLatitude: 49.1265,
    approximateLongitude: -123.183,
    availabilitySummary: "Available to view by appointment",
    includedItems: ["Hitch", "Safety flag"],
    featured: false,
    images: [
      {
        id: "img-wander-3",
        src: "/assets/trailer-bike.jpg",
        storagePath: null,
        alt: "Family bike trailer",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
  {
    ...base,
    ownerId: "00000000-0000-0000-0000-000000000101",
    id: "20000000-0000-0000-0000-000000000001",
    source: "community",
    slug: "community-sage-city-bike",
    title: "Sage City Bike",
    shortDescription: "A simple city bike near the Railway Greenway.",
    description:
      "A well-kept city bike with an upright fit, fenders, and a rear rack. The owner can usually meet in the late afternoon or on weekends.",
    bikeType: "cruiser",
    brand: "Norco",
    model: "Scene",
    frameSize: "Small · 5′1″–5′6″",
    tireSize: "26-inch",
    offerMode: "rent_sale",
    rentalHourlyCents: 900,
    rentalDailyCents: 3500,
    salePriceCents: 36000,
    pickupArea: "Broadmoor",
    approximateLatitude: 49.1474,
    approximateLongitude: -123.1347,
    availabilitySummary: "Weekdays after 4 PM · flexible weekends",
    includedItems: ["Lock", "Rear basket"],
    featured: true,
    images: [
      {
        id: "img-community-1",
        src: "/assets/steveston-ride-idea.jpg",
        storagePath: null,
        alt: "Community city bike in Richmond",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
  {
    ...base,
    ownerId: "00000000-0000-0000-0000-000000000102",
    id: "20000000-0000-0000-0000-000000000002",
    source: "community",
    slug: "community-trail-ready-mountain-bike",
    title: "Trail-ready Mountain Bike",
    shortDescription: "Front suspension and hydraulic brakes for confident rides.",
    description:
      "A dependable hardtail mountain bike maintained by its owner. Suitable for gravel paths and light trails; not offered for downhill riding.",
    bikeType: "mountain",
    brand: "Trek",
    model: "Marlin 6",
    frameSize: "Large · 5′10″–6′2″",
    tireSize: "27.5-inch",
    offerMode: "rent",
    rentalHourlyCents: null,
    rentalDailyCents: 4800,
    salePriceCents: null,
    pickupArea: "Terra Nova",
    approximateLatitude: 49.1687,
    approximateLongitude: -123.1942,
    availabilitySummary: "Friday through Sunday",
    includedItems: ["Helmet", "Lock", "Mini pump"],
    featured: true,
    images: [
      {
        id: "img-community-2",
        src: "/assets/west-dyke-trail.jpg",
        storagePath: null,
        alt: "Community mountain bike near a Richmond trail",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
  {
    ...base,
    ownerId: "00000000-0000-0000-0000-000000000103",
    id: "20000000-0000-0000-0000-000000000003",
    source: "community",
    slug: "community-compact-folding-bike",
    title: "Compact Folding Bike",
    shortDescription: "Easy to store, carry, and take on transit.",
    description:
      "A compact folding bike in good working condition. It folds in under a minute and fits easily in a car trunk or apartment closet.",
    bikeType: "folding",
    brand: "Dahon",
    model: "Mariner",
    frameSize: "One size",
    tireSize: "20-inch",
    offerMode: "sale",
    rentalHourlyCents: null,
    rentalDailyCents: null,
    salePriceCents: 42500,
    pickupArea: "Richmond City Centre",
    approximateLatitude: 49.1666,
    approximateLongitude: -123.1336,
    availabilitySummary: "Available to view evenings",
    includedItems: ["Carry cover"],
    featured: false,
    images: [
      {
        id: "img-community-3",
        src: "/assets/garry-point-park.jpg",
        storagePath: null,
        alt: "Compact folding bike listed by a community owner",
        width: null,
        height: null,
        sortOrder: 0,
      },
    ],
  },
];
