-- Locked-layout website CMS. Marketplace operational data remains separate.

create table if not exists public.website_pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  path text not null unique,
  title text not null,
  draft_content jsonb not null default '{}'::jsonb,
  published_content jsonb not null default '{}'::jsonb,
  draft_updated_at timestamptz not null default now(),
  published_at timestamptz,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint website_pages_slug_shape
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint website_pages_path_shape
    check (path = '/' or path ~ '^/[a-z0-9]+(?:[-/][a-z0-9]+)*$'),
  constraint website_pages_draft_object
    check (jsonb_typeof(draft_content) = 'object'),
  constraint website_pages_published_object
    check (jsonb_typeof(published_content) = 'object')
);

create table if not exists public.website_page_versions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.website_pages(id) on delete cascade,
  version_number integer not null,
  content jsonb not null,
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint website_page_versions_content_object
    check (jsonb_typeof(content) = 'object'),
  constraint website_page_versions_number_positive
    check (version_number > 0),
  unique (page_id, version_number)
);

create index if not exists website_page_versions_page_created_idx
  on public.website_page_versions (page_id, created_at desc);

alter table public.website_pages enable row level security;
alter table public.website_pages force row level security;
alter table public.website_page_versions enable row level security;
alter table public.website_page_versions force row level security;

create policy website_pages_no_client_access
on public.website_pages
for all
to anon, authenticated
using (false)
with check (false);

create policy website_page_versions_no_client_access
on public.website_page_versions
for all
to anon, authenticated
using (false)
with check (false);

revoke all on table public.website_pages
from public, anon, authenticated;
revoke all on table public.website_page_versions
from public, anon, authenticated;
grant all on table public.website_pages to service_role;
grant all on table public.website_page_versions to service_role;
grant usage, select on sequence public.website_pages_id_seq to service_role;
grant usage, select on sequence public.website_page_versions_id_seq to service_role;

insert into public.website_pages (
  slug,
  path,
  title,
  draft_content,
  published_content
)
values ('home', '/', 'Home', '{}'::jsonb, '{}'::jsonb)
on conflict (slug) do nothing;

create or replace function public.publish_website_page(
  p_slug text,
  p_actor_id uuid
)
returns public.website_pages
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_page public.website_pages;
  v_next_version integer;
begin
  update public.website_pages
  set published_content = draft_content,
      published_at = now(),
      updated_at = now(),
      updated_by = p_actor_id
  where slug = p_slug
  returning * into v_page;

  if v_page.id is null then
    raise exception 'Website page not found';
  end if;

  select coalesce(max(version_number), 0) + 1
  into v_next_version
  from public.website_page_versions
  where page_id = v_page.id;

  insert into public.website_page_versions (
    page_id,
    version_number,
    content,
    published_by
  )
  values (
    v_page.id,
    v_next_version,
    v_page.published_content,
    p_actor_id
  );

  return v_page;
end;
$$;

revoke all on function public.publish_website_page(text, uuid)
from public, anon, authenticated;
grant execute on function public.publish_website_page(text, uuid)
to service_role;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'website-media',
  'website-media',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

comment on table public.website_pages is
  'Draft and published content for locked-layout public website pages. Marketplace data is not stored here.';
comment on table public.website_page_versions is
  'Immutable snapshot created each time a website page is published.';
